### PR TITLE
feat: Basic authentication up and running

### PR DESCRIPTION
**Pull request by Vyryty**
This is not enough to complete my backlog item, but I've added the basic login and logout functionality. No advanced permissions or anything of that nature yet, though. Now once the frontend is ready, everyone should be able to login, logout, and have basic authorization when trying to send requests to the database.

### CODE REVIEW

**Review by JessicaVaughan2022 — APPROVED** [review]
Looks good.

**Review by LongShotPlaya — APPROVED** [review]
Looks good to me!

**Review by DeviFitz — APPROVED** [review]
Good job!

**Review by WilsonTrin — APPROVED** [review]
yes

**Pull request merged**
